name: CI — Lint HTML & CSS

on:
  push:
    branches: [ main, workingbench ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint HTML & CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # prefer clean install with lockfile, but fall back to `npm install` if lockfile is missing
        run: npm ci || npm install --no-audit --no-fund

      - name: Lint HTML (html-validate)
        run: npm run lint:html

      - name: Lint CSS (stylelint)
        run: npm run lint:css
